### ISSUE TITLE
Reproduce

### ISSUE THREAD

**Issue by PeterBishop0** [dlwns147/FakeTagger#1]
Hi, thanks for sharing great work! I am wondering if you can provide more detailed illustration about setting up the environment and the pre-trained weights? So that I can reproduce your work!

**Comment by dlwns147** [comment]
Hi! I will attach English version soon. Unfortunately, I don't have pretrained model right now, but its training process is not too long, so you can easily reproduce results. Thank you for your interest in this work!

**Comment by PeterBishop0** [comment]
Got it, thanks again!
